import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ReportView from "@/components/website-audit/ReportView";
import { readInitialWebsiteAuditState } from "@/lib/website-audit/report-state";
import { isWebsiteAuditEnabled } from "@/lib/website-audit/runtime-config";
import styles from "@/components/website-audit/website-audit.module.css";

const auditIdPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export const metadata: Metadata = {
  title: "Website Audit Report",
  description: "A website audit report generated by Veriq.",
  robots: {
    index: false,
    follow: false,
    nocache: true,
  },
};

export const dynamic = "force-dynamic";

export default async function WebsiteAuditReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  if (!isWebsiteAuditEnabled() || !auditIdPattern.test(id)) {
    notFound();
  }

  // A missing record may be an interrupted client-side creation. Preserve the
  // existing recovery flow by letting ReportView retry it from sessionStorage.
  const initialAudit = await readInitialWebsiteAuditState(id).catch(() => null);

  return (
    <main id="main-content" className={`${styles.page} ${styles.reportPage}`}>
      <ReportView auditId={id} initialAudit={initialAudit} />
    </main>
  );
}
